# Generated by Django 3.2.6 on 2021-08-12 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='uploadid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductOwn',
        ),
    ]
