# Generated by Django 3.2.6 on 2021-08-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grade',
        ),
    ]
