# Generated by Django 3.2.6 on 2021-08-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='date_added',
        ),
    ]
