# Generated by Django 3.2.7 on 2021-09-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
